set_value:
  name: Set value
  description: Sets configuration value.
  target:
    entity:
      domain: 4heat
  fields:
    entity_id:
      description: id of the entiy to set
      example: "sensor.something"
      required: true
      selector:
        text:
    value:
      description: value to set
      example: "5"
      required: true
      selector:
        number:
turn_on:
  name: Turn on
  description: Turn 4heat device on.
  target:
    entity:
      domain: 4heat

turn_off:
  name: Turn off
  description: Turn 4heat device off.
  target:
    entity:
      domain: 4heat